version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=templateDatabase
    ports:
      - '3307:3306'

  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "80:8080"
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone/templateDatabase?serverTimezone=America/Los_Angeles
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: './'
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
